// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
export namespace models {
	
	export class Link {
	    skillId: string;
	    mode: string;
	    lastSyncedHash: string;
	    lastSyncedAt: string;
	
	    static createFrom(source: any = {}) {
	        return new Link(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.skillId = source["skillId"];
	        this.mode = source["mode"];
	        this.lastSyncedHash = source["lastSyncedHash"];
	        this.lastSyncedAt = source["lastSyncedAt"];
	    }
	}
	export class Agent {
	    id: string;
	    name: string;
	    displayName: string;
	    path: string;
	    color: string;
	    defaultMode: string;
	    links: Link[];
	
	    static createFrom(source: any = {}) {
	        return new Agent(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.id = source["id"];
	        this.name = source["name"];
	        this.displayName = source["displayName"];
	        this.path = source["path"];
	        this.color = source["color"];
	        this.defaultMode = source["defaultMode"];
	        this.links = this.convertValues(source["links"], Link);
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
	        if (!a) {
	            return a;
	        }
	        if (a.slice && a.map) {
	            return (a as any[]).map(elem => this.convertValues(elem, classs, asMap));
	        } else if ("object" === typeof a) {
	            if (asMap) {
	                for (const key of Object.keys(a)) {
	                    a[key] = new classs(a[key]);
	                }
	                return a;
	            }
	            return new classs(a);
	        }
	        return a;
	    }
	}
	export class Skill {
	    id: string;
	    name: string;
	    description: string;
	    contentHash: string;
	    updatedAt: string;
	
	    static createFrom(source: any = {}) {
	        return new Skill(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.id = source["id"];
	        this.name = source["name"];
	        this.description = source["description"];
	        this.contentHash = source["contentHash"];
	        this.updatedAt = source["updatedAt"];
	    }
	}
	export class HistoryEntry {
	    id: string;
	    timestamp: string;
	    action: string;
	    skillId: string;
	    skillName: string;
	    agentId: string;
	    agentName: string;
	    mode: string;
	    beforeHash?: string;
	    afterHash?: string;
	    backupPath?: string;
	    note?: string;
	
	    static createFrom(source: any = {}) {
	        return new HistoryEntry(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.id = source["id"];
	        this.timestamp = source["timestamp"];
	        this.action = source["action"];
	        this.skillId = source["skillId"];
	        this.skillName = source["skillName"];
	        this.agentId = source["agentId"];
	        this.agentName = source["agentName"];
	        this.mode = source["mode"];
	        this.beforeHash = source["beforeHash"];
	        this.afterHash = source["afterHash"];
	        this.backupPath = source["backupPath"];
	        this.note = source["note"];
	    }
	}
	export class Base {
	    path: string;
	    skills: Skill[];
	
	    static createFrom(source: any = {}) {
	        return new Base(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.path = source["path"];
	        this.skills = this.convertValues(source["skills"], Skill);
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
	        if (!a) {
	            return a;
	        }
	        if (a.slice && a.map) {
	            return (a as any[]).map(elem => this.convertValues(elem, classs, asMap));
	        } else if ("object" === typeof a) {
	            if (asMap) {
	                for (const key of Object.keys(a)) {
	                    a[key] = new classs(a[key]);
	                }
	                return a;
	            }
	            return new classs(a);
	        }
	        return a;
	    }
	}
	export class Config {
	    base: Base;
	    agents: Agent[];
	    history: HistoryEntry[];
	
	    static createFrom(source: any = {}) {
	        return new Config(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.base = this.convertValues(source["base"], Base);
	        this.agents = this.convertValues(source["agents"], Agent);
	        this.history = this.convertValues(source["history"], HistoryEntry);
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
	        if (!a) {
	            return a;
	        }
	        if (a.slice && a.map) {
	            return (a as any[]).map(elem => this.convertValues(elem, classs, asMap));
	        } else if ("object" === typeof a) {
	            if (asMap) {
	                for (const key of Object.keys(a)) {
	                    a[key] = new classs(a[key]);
	                }
	                return a;
	            }
	            return new classs(a);
	        }
	        return a;
	    }
	}
	export class ConfigResponse {
	    config: Config;
	    statusMatrix: Record<string, any>;
	
	    static createFrom(source: any = {}) {
	        return new ConfigResponse(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.config = this.convertValues(source["config"], Config);
	        this.statusMatrix = source["statusMatrix"];
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
	        if (!a) {
	            return a;
	        }
	        if (a.slice && a.map) {
	            return (a as any[]).map(elem => this.convertValues(elem, classs, asMap));
	        } else if ("object" === typeof a) {
	            if (asMap) {
	                for (const key of Object.keys(a)) {
	                    a[key] = new classs(a[key]);
	                }
	                return a;
	            }
	            return new classs(a);
	        }
	        return a;
	    }
	}
	export class SyncResult {
	    config: Config;
	    statusMatrix: Record<string, any>;
	    historyEntry?: HistoryEntry;
	    actualMode: string;
	    degraded: boolean;
	
	    static createFrom(source: any = {}) {
	        return new SyncResult(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.config = this.convertValues(source["config"], Config);
	        this.statusMatrix = source["statusMatrix"];
	        this.historyEntry = this.convertValues(source["historyEntry"], HistoryEntry);
	        this.actualMode = source["actualMode"];
	        this.degraded = source["degraded"];
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
	        if (!a) {
	            return a;
	        }
	        if (a.slice && a.map) {
	            return (a as any[]).map(elem => this.convertValues(elem, classs, asMap));
	        } else if ("object" === typeof a) {
	            if (asMap) {
	                for (const key of Object.keys(a)) {
	                    a[key] = new classs(a[key]);
	                }
	                return a;
	            }
	            return new classs(a);
	        }
	        return a;
	    }
	}
	export class DriftResult {
	    config: Config;
	    statusMatrix: Record<string, any>;
	    newSkillId: string;
	
	    static createFrom(source: any = {}) {
	        return new DriftResult(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.config = this.convertValues(source["config"], Config);
	        this.statusMatrix = source["statusMatrix"];
	        this.newSkillId = source["newSkillId"];
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
	        if (!a) {
	            return a;
	        }
	        if (a.slice && a.map) {
	            return (a as any[]).map(elem => this.convertValues(elem, classs, asMap));
	        } else if ("object" === typeof a) {
	            if (asMap) {
	                for (const key of Object.keys(a)) {
	                    a[key] = new classs(a[key]);
	                }
	                return a;
	            }
	            return new classs(a);
	        }
	        return a;
	    }
	}
	export class BrowseEntry {
	    name: string;
	    isDir: boolean;
	
	    static createFrom(source: any = {}) {
	        return new BrowseEntry(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.name = source["name"];
	        this.isDir = source["isDir"];
	    }
	}
	export class BrowseResult {
	    path: string;
	    parent: string;
	    entries: BrowseEntry[];
	
	    static createFrom(source: any = {}) {
	        return new BrowseResult(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.path = source["path"];
	        this.parent = source["parent"];
	        this.entries = this.convertValues(source["entries"], BrowseEntry);
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
	        if (!a) {
	            return a;
	        }
	        if (a.slice && a.map) {
	            return (a as any[]).map(elem => this.convertValues(elem, classs, asMap));
	        } else if ("object" === typeof a) {
	            if (asMap) {
	                for (const key of Object.keys(a)) {
	                    a[key] = new classs(a[key]);
	                }
	                return a;
	            }
	            return new classs(a);
	        }
	        return a;
	    }
	}
	export class ChangeItem {
	    skill: Skill;
	    agents: ChangeAffectedAgent[];
	
	    static createFrom(source: any = {}) {
	        return new ChangeItem(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.skill = this.convertValues(source["skill"], Skill);
	        this.agents = this.convertValues(source["agents"], ChangeAffectedAgent);
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
	        if (!a) {
	            return a;
	        }
	        if (a.slice && a.map) {
	            return (a as any[]).map(elem => this.convertValues(elem, classs, asMap));
	        } else if ("object" === typeof a) {
	            if (asMap) {
	                for (const key of Object.keys(a)) {
	                    a[key] = new classs(a[key]);
	                }
	                return a;
	            }
	            return new classs(a);
	        }
	        return a;
	    }
	}
	export class ChangeAffectedAgent {
	    agentId: string;
	    agentName: string;
	    status: string;
	
	    static createFrom(source: any = {}) {
	        return new ChangeAffectedAgent(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.agentId = source["agentId"];
	        this.agentName = source["agentName"];
	        this.status = source["status"];
	    }
	}
	export class BatchSyncResult {
	    config: Config;
	    statusMatrix: Record<string, any>;
	    errors: BatchSyncError[];
	    degradedCount: number;
	
	    static createFrom(source: any = {}) {
	        return new BatchSyncResult(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.config = this.convertValues(source["config"], Config);
	        this.statusMatrix = source["statusMatrix"];
	        this.errors = this.convertValues(source["errors"], BatchSyncError);
	        this.degradedCount = source["degradedCount"];
	    }
	
		convertValues(a: any, classs: any, asMap: boolean = false): any {
	        if (!a) {
	            return a;
	        }
	        if (a.slice && a.map) {
	            return (a as any[]).map(elem => this.convertValues(elem, classs, asMap));
	        } else if ("object" === typeof a) {
	            if (asMap) {
	                for (const key of Object.keys(a)) {
	                    a[key] = new classs(a[key]);
	                }
	                return a;
	            }
	            return new classs(a);
	        }
	        return a;
	    }
	}
	export class BatchSyncError {
	    skillId: string;
	    agentId: string;
	    error: string;
	
	    static createFrom(source: any = {}) {
	        return new BatchSyncError(source);
	    }
	
	    constructor(source: any = {}) {
	        if ('string' === typeof source) source = JSON.parse(source);
	        this.skillId = source["skillId"];
	        this.agentId = source["agentId"];
	        this.error = source["error"];
	    }
	}
	
}
