// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddAgent'](arg1, arg2, arg3, arg4);
}

export function Browse(arg1) {
  return window['go']['main']['App']['Browse'](arg1);
}

export function DeleteAgent(arg1, arg2) {
  return window['go']['main']['App']['DeleteAgent'](arg1, arg2);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetChanges() {
  return window['go']['main']['App']['GetChanges']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PushChanges(arg1, arg2) {
  return window['go']['main']['App']['PushChanges'](arg1, arg2);
}

export function ResolveDrift(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResolveDrift'](arg1, arg2, arg3, arg4);
}

export function Rollback(arg1) {
  return window['go']['main']['App']['Rollback'](arg1);
}

export function ScanBase() {
  return window['go']['main']['App']['ScanBase']();
}

export function SetBase(arg1) {
  return window['go']['main']['App']['SetBase'](arg1);
}

export function SyncBatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncBatch'](arg1, arg2, arg3);
}

export function SyncSkill(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncSkill'](arg1, arg2, arg3);
}

export function UnsyncSkill(arg1, arg2) {
  return window['go']['main']['App']['UnsyncSkill'](arg1, arg2);
}

export function UpdateAgent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateAgent'](arg1, arg2, arg3, arg4, arg5);
}
