// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAgent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.ConfigResponse>;

export function Browse(arg1:string):Promise<models.BrowseResult>;

export function DeleteAgent(arg1:string,arg2:boolean):Promise<models.ConfigResponse>;

export function GetAgents():Promise<Array<models.Agent>>;

export function GetChanges():Promise<Array<models.ChangeItem>>;

export function GetConfig():Promise<models.ConfigResponse>;

export function GetHistory(arg1:number):Promise<Array<models.HistoryEntry>>;

export function OpenPath(arg1:string):Promise<void>;

export function PushChanges(arg1:string,arg2:string):Promise<models.SyncResult>;

export function ResolveDrift(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.DriftResult>;

export function Rollback(arg1:string):Promise<models.ConfigResponse>;

export function ScanBase():Promise<models.ConfigResponse>;

export function SetBase(arg1:string):Promise<models.ConfigResponse>;

export function SyncBatch(arg1:Array<string>,arg2:Array<string>,arg3:string):Promise<models.BatchSyncResult>;

export function SyncSkill(arg1:string,arg2:string,arg3:string):Promise<models.SyncResult>;

export function UnsyncSkill(arg1:string,arg2:string):Promise<models.SyncResult>;

export function UpdateAgent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.ConfigResponse>;
